language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php ./composer.phar install --dev

script: phpunit --configuration phpunit.xml.dist